updating cd to new aws account

diff --git a/.github/workflows/CD.yml b/.github/workflows/CD.yml
--- a/.github/workflows/CD.yml
+++ b/.github/workflows/CD.yml
@@ -21,16 +21,40 @@ jobs:
     steps:
         - uses: actions/checkout@v2
 
+        - name: Set AWS Account ID
+          run: |
+            if [[ "${{ github.ref_name }}" == "dev" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_DEV }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_HOMOLOG }}" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "prod" ]]; then
+              echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID_PROD }}" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name!" && exit 1
+            fi
+
+        - name: Setting stage and stack name
+          run: |
+            echo "STAGE=${{ github.ref_name }}" 
+            if [[ "${{ github.ref_name }}" == "prod" ]]; then
+              echo "STAGE=prod" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "homolog" ]]; then
+              echo "STAGE=homolog" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "dev" ]]; then
+              echo "STAGE=dev" >> $GITHUB_ENV
+            elif [[ "${{ github.ref_name }}" == "fix/githubActions" ]]; then
+              echo "STAGE=dev" >> $GITHUB_ENV
+            else
+              echo "Invalid branch name!" && exit 1
+            fi
+            echo "STACK_NAME=DevMediasStack${{github.ref_name}}" >> $GITHUB_ENV
+
         - name: Setup AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-region: ${{ vars.AWS_REGION }}
-            role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GithubActionsRole
+            role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/GithubActionsRole
             role-session-name: github-action
-
-        - name: Setting stage and stack name
-          run: |
-              echo "STACK_NAME=DevMediasStack${{github.ref_name}}" >> $GITHUB_ENV
 
         - name: Installing Dependencies
           run: |
@@ -45,7 +69,7 @@ jobs:
             cdk synth
             cdk deploy --require-approval never
           env:
-            AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
+            AWS_ACCOUNT_ID: ${{ env.AWS_ACCOUNT_ID }}
             AWS_REGION: ${{ vars.AWS_REGION }}
             STACK_NAME: ${{ env.STACK_NAME }}
             GITHUB_REF_NAME: ${{ github.ref_name }}
